In [1]:
import sympy

# Mersenne Prime (메르센 소수)

### 메르센?
- 마린 메르센(1588-1648)은 프랑스 수도승으로 페르마, 파스칼, 갈릴레오 등과 동시대를 산 인물
- 당시에는 수학 저널 같은 것이 없어서 메르센은 수학에서의 발견을 받아 정리하고 배포하는 역할(clearing house)을 했다고 함
- 물론 본인도 철학자이면서 수학자

### 소수를 공식으로 표현하고자 하는 노력
- 무한대의 소수가 있음을 증명할 수 있는 간단한 방법
- $x^{2} + x + 41$이 대표적

In [2]:
[i for i in range(1, 50) if not sympy.ntheory.isprime(i * i + i + 41)]


[40, 41, 44, 49]

1~39까지는 참이지만 40부터 성립하지 않는 결과가 나오기 시작

### Mersenne numbers and primes
- 메르센도 공식을 하나 만들었다. $M_{n} = 2^{n} - 1$
- 이 수를 Mersenne numbers라고 불렀고 이 중 소수인 숫자가 Mersenne prime이라고 불린다
- $n$이 소수가 아니면 $M_{n}$도 소수가 아니다
- $n$이 소수면?

In [3]:
primes = [sympy.prime(n) for n in range(1, 9)]
[(n, 2 ** n - 1, sympy.ntheory.isprime(2 ** n - 1)) for n in primes]

[(2, 3, True),
 (3, 7, True),
 (5, 31, True),
 (7, 127, True),
 (11, 2047, False),
 (13, 8191, True),
 (17, 131071, True),
 (19, 524287, True)]

- 11을 제외하고 19까지 공식이 성립한 걸 본 메르센은 19 이상의 소수에 대해 조사를 하기 시작 ~~수도승은 시간이 많았겠...~~
- $M_{31}$, $M_{67}$, $M_{127}$, $M_{257}$이 소수라고 결론

In [4]:
[(n, 2 ** n - 1, sympy.ntheory.isprime(2 ** n - 1)) for n in [31, 67, 127, 257]]

[(31, 2147483647, True),
 (67, 147573952589676412927, False),
 (127, 170141183460469231731687303715884105727, True),
 (257,
  231584178474632390847141970017375815706539969331281128078915168015826259279871,
  False)]

- 메르센이 어떻게 이 숫자 찾은 과정은 알려지지 않음
- $M_{31}$만 해도 10자리 숫자로 아주 큰 숫자 ~~당시 기술로는 ...~~

### 그 후
- 1750년 오일러 형님이 $M_{31}$은 소수가 맞다고 증명
- 1876년 Edouard Lucas가 $M_{67}$이 소수가 아니라고 발표했지만 어떤 수로 소인수분해되는지는 밝히지 못함
- 이후 Derrick Lehmer라는 사람이 Lucas의 방법을 간결하게 개선

In [5]:
def lucas(p):
    U = 4
    Mp = 2 ** p - 1
    for _ in range(p - 2):
        U = (U * U - 2) % Mp
    return U == 0

In [6]:
[lucas(p) for p in (31, 67, 127, 257)]

[True, False, True, False]

- 된다! 근데 왜 되는거지? ~~저는 몰라요~~
- 그 뒤로도 $M_{61}$, $M_{89}$, $M_{107}$이 메르센 소수임이 밝혀짐
- 결론적으로 메르센 형님의 찍기는 반타작: $M_{31}$(O), $M_{67}$(X), $M_{127}$(O), $M_{257}$(X) ~~많은 수학자들을 낚아 이걸 증명하게 만든 것은 큰 그림~~

### $M_{67}$의 소인수 분해
- Lucas의 방법으로 $M_{67}$이 소수가 아닌 건 알았지만 이 수는 어떤 수들의 곱인지는 밝혀지지 않은 상황
- 1903년, 수학자 Frank Nelson Cole(1861-1926)은 American Mathematical Society에서 'On the Factorisation of Large Numbers'라는 강의를 하게 되는데...
- 아무말 하지 않고 $2^{67}$을 계산하기 시작, 그리고 1을 신중하게(carefully) 뺀다
- 이 숫자는 무려

In [7]:
m67 = 2**67 - 1
print('{:_}'.format(m67))

147_573_952_589_676_412_927


- 그리고 다른 칠판에 193,707,721와 761,838,257,287를 쓰고 곱하기 시작

In [8]:
193_707_721 * 761_838_257_287

147573952589676412927

- 아무 말 없이 계산을 끝냈고, Cole은 기립 박수를 받음
- Cole이 후에 밝히길 이걸 찾아내는데 매주 일요일을 투자했고 3년이 걸렸다고 함

In [9]:
sympy.ntheory.isprime(2**67 - 1)

False

In [10]:
sympy.factorint(2**67 - 1)

{193707721: 1, 761838257287: 1}

- 컴퓨터가 발전하면서 그 뒤로 많은 메르센 소수가 발견되었음
- [GIMPS(Great Internet Mersenne Prime Search) 프로젝트](https://www.mersenne.org/)가 있고 Prime95라는 소프트웨어를 제공
- 이 소프트웨어는 CPU & GPU의 성능을 최대로 활용하기 때문에 오버클럭 후 안정성 테스트에 사용하기도 함
- 2018년 1월 3일 50번째 메르센 소수가 발견됨 : $2^{77,232,917}-1$
- 23,249,425 digits
- 발견 당시 인류가 알고 있는 가장 큰 소수
- 50번째 메르센 발견 시점에서 **증명된 가장 큰 메르센 소수**는 $M_{37156667}$로 45번째 메르센 소수 (검증에 8년 소요)